### ISSUE TITLE
Inside Jekyll tags

### ISSUE THREAD

**Issue by tfoote** [chcokr/remark-lint-sentence-newline#11]
I'm using this on Jekyll pages and they use dot notation for accessing page metadata inside double curly braces. Such as 

```
{{ page.author }}
```

Which gets flagged as a warning. It would be great to add this as an exception, maybe enabled in the config.

**Comment by why-jay** [comment]
Thanks so much for motivating me to get working on this repo! I'll get back within the next couple of days - really busy today.

**Comment by tfoote** [comment]
You're welcome. It's a very useful feature which was our deciding factor for choosing to use mdast.

**Comment by why-jay** [comment]
So sorry for not getting back to you - I'm somehow incredibly busy these few weeks. Will get back to you as soon as I can.

**Comment by why-jay** [comment]
Hey @tfoote, Sorry for being so slow on this. Our detection behavior is now so that an end of sentence (`.`, `!`, `?`, `."`) has to be **followed by a space** in order to be detected. I believe this should resolve your issues with Jekyll tags. I'd love your feedback!

**Comment by tfoote** [comment]
Thanks that should take care of my use case with jekyll.
