### ISSUE TITLE
Don't complain inside quotes

### ISSUE THREAD

**Issue by why-jay** [chcokr/remark-lint-sentence-newline#4]

**Comment by why-jay** [comment]
I'm no longer sure why this should be the case.

**Comment by why-jay** [comment]
Oh, I think this is talking about `."`

**Comment by dirk-thomas** [comment]
I am not sure if the new behavior makes sense. In the following sentence I don't think it makes sense to require a newline:

```
Alice asked me "how was your holiday?" on the telephone.
```

I interpreted the label of the ticket exactly the other way around. Before requiring a space following the dot / question mark it was warning about the missing newline which I though was not desired. But with the new behavior which needs a space afterwards I though the desired goal was already achieved - to not force a newline here.

**Comment by why-jay** [comment]
Hmmmmm...... Your point is valid. I might just revoke the behavior.

@wooorm thoughts?

I'm sure there are cases where a newline after `."` (or whatever) would be desired, but can't think of one right now. If so, I think it'll come down to pros and cons of the new behavior within the boundaries of not being tied to any language.

Should I revoke this behavior? Feedback welcome.

**Comment by wooorm** [comment]
Maybe a better way to detect a sentence break is also by checking whether after the terminal-marker, there’s a upper-cases letter. Thus, `holiday?" on` is not a sentence break by `holiday?" On` is.

**Comment by dirk-thomas** [comment]
I don't think that the case of the following letter can be used for that. E.g. any name would be upper case but doesn't imply a new sentence.

I would rather avoid any false positives even if that means there are some false negatives left.

**Comment by why-jay** [comment]
I agree with @dirk-thomas. If one wants to add a newline, we should allow the freedom to do so. But we should not force it. I'm going to merge @dirk-thomas's PR #21

**Comment by why-jay** [comment]
Do you guys think this is a breaking change? Should I update the major version?

**Comment by wooorm** [comment]
Yup, go for it :)

**Comment by dirk-thomas** [comment]
The change was inserted just two days ago. I would just release a minor (or even patch).

Anyway I am looking forward to use the upcoming version for our stuff :wink: Thanks.

**Comment by wooorm** [comment]
I normally wouldn’t care much either, the number of users is quite low and the chances of breaking builds is small, but still, they’re definitely breaking, so if you want to be more correct, go for a major!

**Comment by why-jay** [comment]
I'll go for a major bump. Thanks for the input.

**Comment by dirk-thomas** [comment]
Are you going to release soon so that users can use this or are you waiting for other changes?

**Comment by why-jay** [comment]
I'll release it today.

On Tuesday, January 12, 2016, Dirk Thomas notifications@github.com wrote:

> Are you going to release soon so that users can use this or are you
> waiting for other changes?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chcokr/remark-lint-sentence-newline/issues/4#issuecomment-170978023
> .

##
